site_name: Development Seed MkDocs
repo_name: developmentseed/ds-mkdocs
repo_url: https://github.com/developmentseed/ds-mkdocs
site_description: The simplest, highest-throughput Python interface to S3, GCS & Azure Storage, powered by Rust.
site_author: Development Seed
# Note: trailing slash recommended with mike:
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#publishing-a-new-version
site_url: https://developmentseed.org/ds-mkdocs/
docs_dir: docs

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/bluesky"
      link: "https://bsky.app/profile/developmentseed.org"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/development-seed"
  version:
    alias: true
    provider: mike

nav:
  - Home: index.md

watch:
  - docs

theme:
  language: en
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_no_text.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.share

extra_css:
  - overrides/stylesheets/extra.css

plugins:
  - blog
  - search
  - social:
      enabled: !ENV [CI, false]
  - mike:
      alias_type: "copy"
      canonical_version: "latest"

# https://github.com/developmentseed/titiler/blob/50934c929cca2fa8d3c408d239015f8da429c6a8/docs/mkdocs.yml#L115-L140
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true